package org.systemsbiology.xtandem;

import java.io.*;
import java.util.*;

/**
 * org.systemsbiology.xtandem.BioMLReportWriter
 *
 * @author Steve Lewis
 * @date Dec 21, 2010
 */

/**
 * write a bioml file from a collecton of protein sequences
 */
public class BioMLReportWriter
{
    public static BioMLReportWriter[] EMPTY_ARRAY = {};
    public static Class THIS_CLASS = BioMLReportWriter.class;

    public static String write(Collection<ProteinSequence> sequences)
    {
        StringBuilder sb = new StringBuilder();
        write(sb, sequences);
        return sb.toString();
    }


    public static void write(Appendable wtr, Collection<ProteinSequence> sequences)
    {
        try {
            wtr.append("<?xml version=\"1.0\"?>\n");
            wtr.append("<!-- generated by jxtandem -->\n");
            wtr.append("<bioml>\n");
               for (ProteinSequence seq : sequences) {
                wtr.append(write(seq));
            }
            wtr.append("</bioml>\n");
        }
        catch (IOException e) {
            throw new RuntimeException(e);
        }

    }

    public static String write(ProteinSequence seq)
    {
        StringBuilder sb = new StringBuilder();

        final String strSequence = seq.getStrSeq();
        int tSize = strSequence.length();
        sb.append("<protein label=\"" + seq.getStrDes() + " \" uid=\"" +
                seq.gettUid() + "\">\n");
        sb.append("<file URL=\"" + seq.getStrPath() + "\"/>\n");

        sb.append("<peptide start=\"1\" end=\""  + tSize + "\">\n");
        int b = 0;
        int colc = 1;
        while (b < tSize) {
            char ch =  strSequence.charAt(b++);
            sb.append(ch);
            if (colc++ == 50) {
                sb.append("\n");
                colc = 0;
            }
         }
        sb.append("\n</peptide>\n");
        sb.append("</protein>\n");
        return sb.toString();

    }
 

}
